Support mirror registries with path component
GoogleContainerTools/kaniko pull request #1707
Opened 2021-07-28 14:34 UTC by imjasonh

Fixes #1618

**Description**

This change should allow `--mirror-registry=my.mirror/some/prefix/path`, where previously only repository roots were supported.

This PR doesn't currently include tests that cover this behavior, if there's a good place to add that please let me know.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
--mirror-registry now supports path components
```

2021-07-29 21:29 UTC, imjasonh commented
Tests seem to fail with this error message:
```
        error building image: GET https://gcr.io/v2/kaniko-test/extraction-base-image/manifests/latest: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

This seems unrelated to my change, unless I'm missing something. Is it a flake?

2021-08-11 05:02 UTC, tejal29 requested changes
Thank you for your contribution. 
Please add tests!

2021-08-11 05:03 UTC, tejal29 commented
> Tests seem to fail with this error message:
> 
> ```
>         error building image: GET https://gcr.io/v2/kaniko-test/extraction-base-image/manifests/latest: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
> ```
> 
> This seems unrelated to my change, unless I'm missing something. Is it a flake?

Sorry @imjasonh, somehow internal test project got deleted :(. Doing my best to get it moved and recover.

2021-08-11 05:06 UTC, tejal29 approved these changes
LGTM

2021-08-11 05:06 UTC, tejal29 commented
> Thank you for your contribution.
> Please add tests!

nvm. This is not needed

2021-08-11 05:06 UTC, merged

2024-01-22 18:36 UTC, lionello commented
@imjasonh Do you think this can be fixed to avoid the regressions from the first PR? See #1790 #1791 #1793

2024-04-09 19:38 UTC, Realiserad commented
@tejal29 Why was this reverted? Any plans to add this back again or should we open a new PR?