Chore remove refs to deprecated io/ioutil
GoogleContainerTools/kaniko pull request #2807
Opened 2023-10-18 13:16 UTC by kacperswis

Fixes #<issue number> _in case of a bug fix, this should point to a bug and any other related issue(s)_

**Description**

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

2023-10-25 20:30 UTC, JeromeJu commented
Thanks for the fix @kacperswis would you mind squashing the commits as some of the seems to be "WIP" steps?

2023-10-26 06:36 UTC, kacperswis commented
Do you mean to make another PR and "merge" commits? @JeromeJu

2023-10-26 12:40 UTC, JeromeJu commented
> Do you mean to make another PR and "merge" commits? @JeromeJu

I was referring to the 3 commits in this PR that all come together for the purpose of removing deprecated io/ioutil, where they can [be squashed using command `git rebase -i <previous commit sha>`](https://gist.github.com/lpranam/4ae996b0a4bc37448dc80356efbca7fa):
```
[chore: remove refs to deprecated io/ioutil](https://github.com/GoogleContainerTools/kaniko/pull/2807/commits/f17da1f7ae13a45f802fa974f60de61466992e10)

[Merge branch 'main' into chore-remove-refs-to-deprecated-io/ioutil-](https://github.com/GoogleContainerTools/kaniko/pull/2807/commits/e51b7f48004118c20d2d7555fe2e6ea54079b16f)

[chore: repair of erroneously resolved conflictt](https://github.com/GoogleContainerTools/kaniko/pull/2807/commits/3a1e8e0c2557cee18273edc463b3d8d7d71b3ccb)

```

It'd help other contributors to better understand the PR context if we have a commit dedicated to tackle one specific issue.

2023-10-30 21:17 UTC, aaron-prindle approved these changes
I believe we can squash and merge this on our end directly, going to try that now.  I think there may be some errors w/ this PR from test changes as I am going through this

2023-10-30 21:21 UTC, aaron-prindle requested changes

2023-10-30 21:21 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +			testutil.CheckDeepEqual(t, fi.Mode(), fi.Mode())
This change is not related to the PR goals and actually breaks the test IIUC (comparing `fi.Mode()` w/ `fi.Mode()` now).  This change should likely be undone

2023-10-30 21:26 UTC, aaron-prindle requested changes

2023-10-30 21:26 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +		fi, _ := files[0].Info()
nit: can you just inline this vs making the `fi` var?

2023-10-30 21:26 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +		fi, _ := files[0].Info()
nit: can you just inline this vs making the `fi` var?

2023-10-30 21:26 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +			fi, _ := f.Info()
nit: can you just inline this vs making the `fi` and `afi` var?

2023-10-30 21:26 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +			fi, _ := f.Info()
nit: can you just inline this vs making the `fi` and `afi` var?

2023-10-30 21:26 UTC, aaron-prindle commented on pkg/commands/copy_test.go
> +		fi, _ := actual[0].Info()
nit: can you just inline this vs making the `fi` var?

2023-11-29 03:03 UTC, aaron-prindle commented
https://github.com/GoogleContainerTools/kaniko/issues/2806 is fixed now, closing

2023-11-29 03:03 UTC, closed without merging